services:
  - type: web
    name: complaint-analyzer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: complaint_analyzer
```

### **Step 2.3: Create `runtime.txt`**
Location: `backend/runtime.txt`
```
python-3.11.0